[project]
name = "r1"
version = "0.1.0"
description = "A custom library for loading and generating with R1 models"
readme = "README.md"
authors = [{ name = "Philip Chung" }]
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.3.0",
    "autoawq>=0.2.7.post3",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
    "transformers>=4.48.3",
    "typer>=0.15.1",
    "utils",
]

[tool.uv.sources]
utils = { workspace = true }

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
